package com.internalops.workbench;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.internalops.auth.CurrentUser;
import com.internalops.auth.UserRole;
import com.internalops.customerfund.CustomerFundQueryService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.web.servlet.MockMvc;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Map;
import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc(addFilters = false)
@Sql(scripts = "/sales-command-schema.sql")
class ShippedOrderEditApiTest {
    @Autowired MockMvc mvc;
    @Autowired JdbcTemplate jdbc;
    @Autowired CustomerFundQueryService funds;
    @Autowired InventoryAllocationService allocation;
    private final ObjectMapper mapper = new ObjectMapper();

    @BeforeEach void setup() {
        CurrentUser.set(new CurrentUser(9, "finance", "财务", UserRole.FINANCE));
        jdbc.execute("DROP TABLE IF EXISTS customer_fund_ledger");
        jdbc.execute("DROP TABLE IF EXISTS customer_fund_request");
        jdbc.execute("DROP TABLE IF EXISTS customer_fund_account");
        jdbc.execute("CREATE TABLE customer_fund_account(customer_id BIGINT PRIMARY KEY,balance DECIMAL(19,4),version INT DEFAULT 0,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE customer_fund_request(id BIGINT PRIMARY KEY,customer_id BIGINT,status VARCHAR(20),amount DECIMAL(19,4))");
        jdbc.execute("CREATE TABLE customer_fund_ledger(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT,entry_type VARCHAR(30),direction VARCHAR(10),amount DECIMAL(19,4),balance_before DECIMAL(19,4),balance_after DECIMAL(19,4),request_id BIGINT,source_type VARCHAR(30),source_id BIGINT,source_no VARCHAR(80),reverses_ledger_id BIGINT,reason VARCHAR(1000),operated_by BIGINT,operated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.update("INSERT INTO customer_fund_account(customer_id,balance) VALUES(1,500)");
        jdbc.update("INSERT INTO sales_order(id,order_no,customer_id,status,total_amount,order_date,order_type,salesperson,shipped_at,version) VALUES(801,'DD-EDIT',1,'SHIPPED',100,CURRENT_DATE,'工程订单','销售员',TIMESTAMP '2026-09-01 10:00:00',0)");
        jdbc.update("INSERT INTO sales_order_item(id,sales_order_id,line_no,sku_id,quantity,shipped_quantity,locked_quantity,uncovered_quantity,sale_price,cost_snapshot,item_remark) VALUES(801,801,10000,1,10,10,0,0,10,4,'原备注')");
        jdbc.update("INSERT INTO inventory_balance(warehouse_id,sku_id,actual_quantity,locked_quantity,in_transit_quantity) VALUES(1,1,20,0,7)");
        jdbc.update("INSERT INTO sales_shipment(id,shipment_no,sales_order_id,operator_name,shipped_at) VALUES(801,'FH-EDIT',801,'仓管',TIMESTAMP '2026-09-01 10:00:00')");
        jdbc.update("INSERT INTO sales_shipment_item(id,sales_shipment_id,sales_order_item_id,quantity) VALUES(801,801,801,10)");
        jdbc.execute("ALTER TABLE sales_shipment_item ADD CONSTRAINT fk_edit_shipment_line FOREIGN KEY(sales_order_item_id) REFERENCES sales_order_item(id)");
        jdbc.update("INSERT INTO customer_receipt(sales_order_id,amount,confirmed_amount,payment_method,received_at,review_status) VALUES(801,90,100,'银行转账',CURRENT_TIMESTAMP,'APPROVED')");
        jdbc.update("INSERT INTO customer_receipt(sales_order_id,amount,payment_method,received_at,review_status) VALUES(801,7,'银行转账',CURRENT_TIMESTAMP,'PENDING')");
    }

    @AfterEach void clear() { CurrentUser.clear(); }

    private String body(int quantity, int price, int original, int received, String reason) throws Exception {
        return mapper.writeValueAsString(Map.of("customerId",1,"version",0,"orderDate","2026-09-01","orderType","工程订单","salesperson","销售员",
                "items",java.util.List.of(Map.of("lineNo",10000,"skuId",1,"quantity",quantity,"salePrice",price,"remark","修改后备注")),
                "receiptConfirmation",Map.of("originalAmount",original,"amount",received,"reason",reason)));
    }
    private BigDecimal balance() { return jdbc.queryForObject("SELECT balance FROM customer_fund_account WHERE customer_id=1",BigDecimal.class); }
    private int count(String table) { return jdbc.queryForObject("SELECT COUNT(*) FROM "+table,Integer.class); }

    @Test void editsPriceAndReceiptTogetherWithoutChangingShipmentOrPhysicalStock() throws Exception {
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(10,12,100,120,"按实际结算补记")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("SHIPPED"))
                .andExpect(jsonPath("$.data.items[0].id").value(801)).andExpect(jsonPath("$.data.items[0].shippedQuantity").value(10))
                .andExpect(jsonPath("$.data.items[0].remark").value("修改后备注"))
                .andExpect(jsonPath("$.data.receivedAmount").value(120)).andExpect(jsonPath("$.data.totalAmount").value(120));
        assertThat(balance()).isEqualByComparingTo("480");
        assertThat(jdbc.queryForObject("SELECT actual_quantity FROM inventory_balance WHERE sku_id=1",Integer.class)).isEqualTo(20);
        assertThat(jdbc.queryForObject("SELECT locked_quantity FROM inventory_balance WHERE sku_id=1",Integer.class)).isZero();
        assertThat(jdbc.queryForObject("SELECT quantity FROM sales_shipment_item WHERE id=801",Integer.class)).isEqualTo(10);
        assertThat(jdbc.queryForObject("SELECT amount FROM customer_receipt WHERE review_status='APPROVED' AND payment_method='银行转账'",BigDecimal.class)).isEqualByComparingTo("90");
        assertThat(jdbc.queryForObject("SELECT reason FROM customer_fund_ledger",String.class)).contains("100.00", "120", "按实际结算补记");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM customer_receipt WHERE review_status='PENDING'",Integer.class)).isEqualTo(1);
        assertThat((BigDecimal)funds.overview(1).get("orderOutstandingAmount")).isEqualByComparingTo("0");
        var month=funds.summary(1,"MONTH",LocalDate.now().withDayOfMonth(1),LocalDate.now());
        assertThat((BigDecimal)month.get(0).get("receiptAmount")).isEqualByComparingTo("20");
    }

    @Test void loweringReceiptReturnsBalanceAndUpdatesNetReceiptSummary() throws Exception {
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(10,8,100,80,"订单降价退回余额")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.data.receivedAmount").value(80));
        assertThat(balance()).isEqualByComparingTo("520");
        assertThat(jdbc.queryForObject("SELECT amount FROM customer_receipt WHERE payment_method='订单调整'",BigDecimal.class)).isEqualByComparingTo("-20");
        assertThat((BigDecimal)funds.overview(1).get("orderOutstandingAmount")).isEqualByComparingTo("0");
        assertThat((BigDecimal)funds.summary(1,"DAY",LocalDate.now(),LocalDate.now()).get(0).get("receiptAmount")).isEqualByComparingTo("-20");
    }

    @Test void additionalQuantityReopensOnlyTheUnshippedDemandAndKeepsCoverageHistory() throws Exception {
        jdbc.update("INSERT INTO procurement_suggestion(id,suggestion_no,status) VALUES(801,'CG801','CONFIRMED')");
        jdbc.update("INSERT INTO procurement_suggestion_item(id,suggestion_id,sku_id,supplier_id,shortage_quantity,suggested_quantity,purchase_price) VALUES(801,801,1,201,10,10,1)");
        jdbc.update("INSERT INTO shortage_coverage(id,sales_order_item_id,suggestion_item_id,covered_quantity,active) VALUES(801,801,801,10,TRUE)");
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(15,10,100,100,"")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("READY_TO_SHIP"))
                .andExpect(jsonPath("$.data.items[0].lockedQuantity").value(5)).andExpect(jsonPath("$.data.items[0].remainingQuantity").value(5));
        assertThat(jdbc.queryForObject("SELECT locked_quantity FROM inventory_balance WHERE sku_id=1",Integer.class)).isEqualTo(5);
        assertThat(count("shortage_coverage")).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT active FROM shortage_coverage WHERE id=801",Boolean.class)).isFalse();
        assertThat(count("customer_fund_ledger")).isZero();
    }

    @Test void editsPartialShipmentWithoutDoubleAllocatingShippedUnits() throws Exception {
        jdbc.update("UPDATE sales_order SET status='WAITING_STOCK' WHERE id=801");
        jdbc.update("UPDATE sales_order_item SET quantity=15,locked_quantity=2,uncovered_quantity=3 WHERE id=801");
        jdbc.update("UPDATE inventory_balance SET actual_quantity=3,locked_quantity=2 WHERE sku_id=1");
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(14,10,100,100,"")))
                .andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].lockedQuantity").value(3))
                .andExpect(jsonPath("$.data.items[0].uncoveredQuantity").value(1));
        assertThat(jdbc.queryForObject("SELECT actual_quantity FROM inventory_balance WHERE sku_id=1",Integer.class)).isEqualTo(3);
        // Receipt of more inventory uses this same allocator and must still exclude shipped units.
        jdbc.update("UPDATE inventory_balance SET actual_quantity=4 WHERE sku_id=1");
        allocation.reallocateWaiting();
        assertThat(jdbc.queryForObject("SELECT locked_quantity FROM inventory_balance WHERE sku_id=1",Integer.class)).isEqualTo(4);
    }

    @Test void cannotRemoveOrReplaceShippedLinesOrReduceBelowShippedQuantity() throws Exception {
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(9,10,100,100,"")))
                .andExpect(status().isBadRequest());
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(10,10,100,100,"").replace("\"skuId\":1","\"skuId\":2")))
                .andExpect(status().isBadRequest());
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(10,10,100,100,"").replace("10000","20000")))
                .andExpect(status().isBadRequest());
        assertThat(count("sales_order_item")).isEqualTo(1);
        assertThat(count("sales_shipment_item")).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT version FROM sales_order WHERE id=801",Integer.class)).isZero();
    }

    @Test void insufficientFundsRollBackOrderPriceInventoryAndAdjustment() throws Exception {
        jdbc.update("UPDATE customer_fund_account SET balance=0 WHERE customer_id=1");
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(12,10,100,120,"补记")))
                .andExpect(status().isBadRequest()).andExpect(jsonPath("$.message").value("客户余额不足"));
        assertThat(jdbc.queryForObject("SELECT quantity FROM sales_order_item WHERE id=801",Integer.class)).isEqualTo(10);
        assertThat(jdbc.queryForObject("SELECT total_amount FROM sales_order WHERE id=801",BigDecimal.class)).isEqualByComparingTo("100");
        assertThat(count("customer_receipt")).isEqualTo(2);
        assertThat(count("customer_fund_ledger")).isZero();
    }

    @Test void requiresConfirmationReasonPermissionAndFreshReceiptSnapshot() throws Exception {
        var noConfirmation=mapper.readTree(body(10,10,100,100,""));
        ((com.fasterxml.jackson.databind.node.ObjectNode)noConfirmation).remove("receiptConfirmation");
        mvc.perform(put("/api/orders/801").contentType("application/json").content(noConfirmation.toString())).andExpect(status().isBadRequest());
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(10,12,100,120," "))).andExpect(status().isBadRequest());
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(10,12,90,120,"补记"))).andExpect(status().isConflict());
        CurrentUser.set(new CurrentUser(3,"user","用户",UserRole.USER));
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(10,12,100,120,"补记"))).andExpect(status().isConflict());
        assertThat(balance()).isEqualByComparingTo("500");
        assertThat(count("customer_fund_ledger")).isZero();
    }

    @Test void repeatedSaveDoesNotDuplicateReceiptAndCustomerCannotBeTransferred() throws Exception {
        jdbc.update("INSERT INTO customer(id,customer_code,customer_name,enabled) VALUES(2,'C2','另一客户',TRUE)");
        mvc.perform(put("/api/orders/801").contentType("application/json").content(body(10,12,100,120,"补记").replace("\"customerId\":1","\"customerId\":2")))
                .andExpect(status().isBadRequest());
        String request=body(10,12,100,120,"补记");
        mvc.perform(put("/api/orders/801").contentType("application/json").content(request)).andExpect(status().isOk());
        mvc.perform(put("/api/orders/801").contentType("application/json").content(request)).andExpect(status().isConflict());
        assertThat(count("customer_fund_ledger")).isEqualTo(1);
        assertThat(balance()).isEqualByComparingTo("480");
    }
}
