DROP TABLE IF EXISTS customer_contract_price;
DROP TABLE IF EXISTS customer_contract;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS sku;
CREATE TABLE customer(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_code VARCHAR(40) UNIQUE NOT NULL,customer_type VARCHAR(20),customer_name VARCHAR(200) NOT NULL,contact_name VARCHAR(100),phone VARCHAR(40),address VARCHAR(500),business_contact_name VARCHAR(100),business_contact_phone VARCHAR(40),order_contact_name VARCHAR(100),order_contact_phone VARCHAR(40),finance_contact_name VARCHAR(100),finance_contact_phone VARCHAR(40),invoice_title VARCHAR(200),taxpayer_id VARCHAR(100),invoice_address VARCHAR(500),invoice_phone VARCHAR(40),bank_name VARCHAR(200),bank_account VARCHAR(100),enabled BOOLEAN DEFAULT TRUE,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,version INT DEFAULT 0);
CREATE TABLE sku(id BIGINT PRIMARY KEY,sku_code VARCHAR(80),product_name VARCHAR(200),model VARCHAR(100),configuration VARCHAR(1000),product_version VARCHAR(80),color VARCHAR(80),lock_body VARCHAR(80),unit VARCHAR(20),enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE customer_contract(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL,contract_no VARCHAR(80) NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,remark VARCHAR(500),enabled BOOLEAN DEFAULT TRUE,version INT DEFAULT 0,UNIQUE(customer_id,contract_no));
CREATE TABLE customer_contract_price(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,contract_id BIGINT NOT NULL,sku_id BIGINT NOT NULL,sale_price DECIMAL(18,4) NOT NULL,UNIQUE(contract_id,sku_id));
INSERT INTO sku VALUES(1,'SKU-1','产品一','M1','规格一',NULL,NULL,NULL,'件',TRUE),(2,'SKU-2','产品二','M2','规格二',NULL,NULL,NULL,'件',TRUE);
INSERT INTO customer(id,customer_code,customer_name,order_contact_name,order_contact_phone,address,enabled) VALUES(1,'ACTIVE','有效客户','订单联系人','13800138000','珠海',TRUE),(2,'EXPIRED','过期客户','旧联系人','13800138001','深圳',TRUE),(3,'NO-CONTRACT','未签合同客户',NULL,NULL,NULL,TRUE);
INSERT INTO customer_contract(id,customer_id,contract_no,start_date,end_date,enabled) VALUES(1,1,'ACTIVE-2026','2026-01-01','2027-12-31',TRUE),(2,2,'OLD-2020','2020-01-01','2020-12-31',TRUE);
INSERT INTO customer_contract_price(contract_id,sku_id,sale_price) VALUES(1,1,456.7800),(2,1,300.0000);

ALTER TABLE sku ADD COLUMN sales_minimum_order_quantity INT NOT NULL DEFAULT 1;
