DROP TABLE IF EXISTS sku_cost_history;
DROP TABLE IF EXISTS inventory_transaction;
DROP TABLE IF EXISTS inventory_locked_allocation;
DROP TABLE IF EXISTS inventory_balance;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS warehouse;
CREATE TABLE customer (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_code VARCHAR(40) UNIQUE NOT NULL, customer_name VARCHAR(200) NOT NULL, enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE supplier (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_code VARCHAR(40) UNIQUE NOT NULL, supplier_name VARCHAR(200) NOT NULL, contact_name VARCHAR(100), phone VARCHAR(100), bank_account VARCHAR(200), manufacturer_category VARCHAR(100), manufacturer_type VARCHAR(100), supplier_location VARCHAR(100), product_attribute VARCHAR(100), short_name VARCHAR(120), contact_title VARCHAR(100), address VARCHAR(500), currency VARCHAR(100), tax_registration_no VARCHAR(100), bank_address VARCHAR(500), enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE warehouse (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_code VARCHAR(40) UNIQUE NOT NULL, warehouse_name VARCHAR(100) NOT NULL, is_default BOOLEAN DEFAULT FALSE, enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE sku (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sku_code VARCHAR(80), model VARCHAR(100), product_name VARCHAR(200) NOT NULL, color VARCHAR(80), lock_body VARCHAR(80), product_version VARCHAR(80), configuration VARCHAR(1000), unit VARCHAR(20) DEFAULT '件', current_cost DECIMAL(18,4), factory_price DECIMAL(18,4), product_remark VARCHAR(500), enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE inventory_balance (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_id BIGINT NOT NULL, sku_id BIGINT NOT NULL, actual_quantity INT DEFAULT 0, locked_quantity INT DEFAULT 0, in_transit_quantity INT DEFAULT 0, source_supplier_name VARCHAR(200), inventory_remark VARCHAR(500), version INT DEFAULT 0, UNIQUE(warehouse_id,sku_id));
CREATE TABLE inventory_locked_allocation (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, inventory_balance_id BIGINT NOT NULL, lock_source VARCHAR(30) NOT NULL, quantity INT NOT NULL DEFAULT 0, UNIQUE(inventory_balance_id, lock_source));
CREATE TABLE inventory_transaction (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_id BIGINT NOT NULL, sku_id BIGINT NOT NULL, transaction_type VARCHAR(40), business_type VARCHAR(40), business_no VARCHAR(80), actual_delta INT, locked_delta INT, transit_delta INT, actual_before INT, actual_after INT, locked_before INT, locked_after INT, transit_before INT, transit_after INT, operated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sku_cost_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sku_id BIGINT NOT NULL, old_cost DECIMAL(18,4), new_cost DECIMAL(18,4) NOT NULL, source_type VARCHAR(40), source_no VARCHAR(80), effective_at TIMESTAMP, operated_by BIGINT);
INSERT INTO warehouse(warehouse_code,warehouse_name,is_default,enabled) VALUES('DEFAULT','默认仓库',TRUE,TRUE);

ALTER TABLE sku ADD COLUMN sales_minimum_order_quantity INT NOT NULL DEFAULT 1;
