DROP TABLE IF EXISTS import_row;
DROP TABLE IF EXISTS import_workbook_row;
DROP TABLE IF EXISTS import_workbook_sheet;
DROP TABLE IF EXISTS import_workbook_file;
DROP TABLE IF EXISTS import_batch;
CREATE TABLE import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_type VARCHAR(20) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    file_hash CHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    error_rows INT NOT NULL DEFAULT 0,
    ignored_rows INT NOT NULL DEFAULT 0,
    committed_rows INT NOT NULL DEFAULT 0,
    result_detail CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    committed_at TIMESTAMP,
    CONSTRAINT uk_import_batch_type_hash UNIQUE(import_type, file_hash)
);
CREATE TABLE import_row (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    source_sheet VARCHAR(100) NOT NULL,
    source_row INT NOT NULL,
    row_status VARCHAR(20) NOT NULL CHECK(row_status IN ('VALID','ERROR','IGNORED')),
    normalized_data CLOB NOT NULL,
    error_message VARCHAR(1000),
    manual_entry BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_import_row_batch FOREIGN KEY(batch_id) REFERENCES import_batch(id)
);
CREATE TABLE import_workbook_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    file_content BLOB NOT NULL,
    CONSTRAINT fk_import_workbook_file_batch FOREIGN KEY(batch_id) REFERENCES import_batch(id)
);
CREATE TABLE import_workbook_sheet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    sheet_index INT NOT NULL,
    sheet_name VARCHAR(255) NOT NULL,
    column_count INT NOT NULL,
    CONSTRAINT fk_import_workbook_sheet_batch FOREIGN KEY(batch_id) REFERENCES import_batch(id)
);
CREATE TABLE import_workbook_row (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    sheet_id BIGINT NOT NULL,
    source_row INT NOT NULL,
    cell_values CLOB NOT NULL,
    CONSTRAINT fk_import_workbook_row_batch FOREIGN KEY(batch_id) REFERENCES import_batch(id),
    CONSTRAINT fk_import_workbook_row_sheet FOREIGN KEY(sheet_id) REFERENCES import_workbook_sheet(id)
);
