DROP TABLE IF EXISTS inventory_transaction;
DROP TABLE IF EXISTS inventory_locked_allocation;
DROP TABLE IF EXISTS user_session;
DROP TABLE IF EXISTS inventory_balance;
DROP TABLE IF EXISTS sku_supplier_config;
DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS product_code_rule;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS warehouse;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS customer;
CREATE TABLE customer(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_code VARCHAR(40) UNIQUE NOT NULL,customer_name VARCHAR(200) NOT NULL,contact_name VARCHAR(100),phone VARCHAR(40),address VARCHAR(500),business_contact_name VARCHAR(100),business_contact_phone VARCHAR(40),order_contact_name VARCHAR(100),order_contact_phone VARCHAR(40),finance_contact_name VARCHAR(100),finance_contact_phone VARCHAR(40),invoice_title VARCHAR(200),taxpayer_id VARCHAR(100),invoice_address VARCHAR(500),invoice_phone VARCHAR(40),bank_name VARCHAR(200),bank_account VARCHAR(100),enabled BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,version INT DEFAULT 0);
CREATE TABLE sys_user(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,username VARCHAR(80) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,display_name VARCHAR(100) NOT NULL,phone VARCHAR(40),enabled BOOLEAN DEFAULT TRUE,role VARCHAR(20) NOT NULL DEFAULT 'USER',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,version INT DEFAULT 0);
CREATE TABLE user_session(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expires_at TIMESTAMP NOT NULL,revoked_at TIMESTAMP,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE warehouse(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,warehouse_code VARCHAR(40) UNIQUE NOT NULL,warehouse_name VARCHAR(100) NOT NULL,is_default BOOLEAN DEFAULT FALSE,enabled BOOLEAN DEFAULT TRUE,version INT DEFAULT 0);
CREATE TABLE supplier(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,supplier_code VARCHAR(40) UNIQUE NOT NULL,supplier_name VARCHAR(200) NOT NULL,enabled BOOLEAN DEFAULT TRUE,version INT DEFAULT 0);
CREATE TABLE product_code_rule(id BIGINT PRIMARY KEY,category VARCHAR(40),code VARCHAR(20),display_name VARCHAR(100),enabled BOOLEAN,sort_order INT,version INT);
CREATE TABLE sku(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,product_code VARCHAR(80),sku_code VARCHAR(80),model VARCHAR(100),product_name VARCHAR(200) NOT NULL,color VARCHAR(80),lock_body VARCHAR(80),product_version VARCHAR(80),configuration VARCHAR(1000),product_configuration VARCHAR(500),unit VARCHAR(20) DEFAULT '件',current_cost DECIMAL(18,4),factory_price DECIMAL(18,4),product_remark VARCHAR(500),enabled BOOLEAN DEFAULT TRUE,brand_rule_id BIGINT,series_rule_id BIGINT,body_color_rule_id BIGINT,lock_type_rule_id BIGINT,connectivity_rule_id BIGINT,sales_channel_rule_id BIGINT,operating_entity_rule_id BIGINT,language_rule_id BIGINT,product_type VARCHAR(30) DEFAULT 'UNCLASSIFIED',material_type VARCHAR(32) NOT NULL DEFAULT 'FINISHED_PRODUCT',door_model_rule_id BIGINT,security_grade_rule_id BIGINT,base_material_rule_id BIGINT,thickness_rule_id BIGINT,finish_color_rule_id BIGINT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,version INT DEFAULT 0);
ALTER TABLE sku ADD COLUMN code_suffix TEXT;
ALTER TABLE sku ADD COLUMN ean_code VARCHAR(12) UNIQUE;
CREATE TABLE sku_supplier_config(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,sku_id BIGINT UNIQUE NOT NULL,supplier_id BIGINT NOT NULL,purchase_price DECIMAL(18,4) NOT NULL,moq INT NOT NULL,lead_time_days INT DEFAULT 0,enabled BOOLEAN DEFAULT TRUE,version INT DEFAULT 0);
CREATE TABLE inventory_balance(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,warehouse_id BIGINT NOT NULL,sku_id BIGINT NOT NULL,actual_quantity INT DEFAULT 0,locked_quantity INT DEFAULT 0,in_transit_quantity INT DEFAULT 0,source_supplier_name VARCHAR(200),inventory_remark VARCHAR(500),updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,version INT DEFAULT 0,UNIQUE(warehouse_id,sku_id));
CREATE TABLE inventory_transaction(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,warehouse_id BIGINT NOT NULL,sku_id BIGINT NOT NULL,transaction_type VARCHAR(40),business_type VARCHAR(40),business_no VARCHAR(80),actual_delta INT,locked_delta INT,transit_delta INT,actual_before INT,actual_after INT,locked_before INT,locked_after INT,transit_before INT,transit_after INT,operated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE inventory_locked_allocation(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,inventory_balance_id BIGINT NOT NULL,lock_source VARCHAR(30) NOT NULL,quantity INT NOT NULL DEFAULT 0,UNIQUE(inventory_balance_id,lock_source));
INSERT INTO warehouse(id,warehouse_code,warehouse_name,is_default) VALUES(1,'WH001','默认仓',TRUE);
INSERT INTO sys_user(id,username,password_hash,display_name,enabled,role) VALUES
(1,'admin','123','管理员',TRUE,'ADMIN'),
(2,'finance','123','财务',TRUE,'FINANCE'),
(3,'regular-user','123','操作员',TRUE,'USER');
INSERT INTO product_code_rule(id,category,code,display_name,enabled,sort_order,version) VALUES
(101,'BRAND','SXSEL','STANLEY',TRUE,10,0),
(102,'BODY_COLOR','YZH','宇宙黑',TRUE,10,0),
(103,'LOCK_TYPE','70','7068',TRUE,10,0),
(104,'LANGUAGE','C','中文版',TRUE,10,0);
INSERT INTO sku(id,product_code,sku_code,product_name,current_cost,factory_price) VALUES(1,'OLD_000001','SKU001','测试产品',10.00,20.00);
INSERT INTO sku(id,product_code,sku_code,product_name) VALUES(2,'OLD_000002','SKU002','测试产品二');
INSERT INTO inventory_balance(id,warehouse_id,sku_id,actual_quantity,locked_quantity,in_transit_quantity,version) VALUES(1,1,1,5,1,0,0);
