DROP TABLE IF EXISTS inventory_transaction;
DROP TABLE IF EXISTS inventory_balance;
DROP TABLE IF EXISTS purchase_order_item;
DROP TABLE IF EXISTS purchase_order;
DROP TABLE IF EXISTS shortage_coverage;
DROP TABLE IF EXISTS procurement_suggestion_item;
DROP TABLE IF EXISTS procurement_suggestion;
DROP TABLE IF EXISTS sku_supplier_config;
DROP TABLE IF EXISTS sales_order_item;
DROP TABLE IF EXISTS sales_order;
DROP TABLE IF EXISTS warehouse;
DROP TABLE IF EXISTS supplier;

CREATE TABLE warehouse(
    id BIGINT PRIMARY KEY,
    is_default BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL
);
CREATE TABLE supplier(
    id BIGINT PRIMARY KEY,
    supplier_name VARCHAR(200) NOT NULL
);
CREATE TABLE sales_order(
    id BIGINT PRIMARY KEY,
    status VARCHAR(40) NOT NULL,
    receipt_confirmed_at TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE sales_order_item(
    id BIGINT PRIMARY KEY,
    sales_order_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    sku_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    locked_quantity INT NOT NULL DEFAULT 0,
    uncovered_quantity INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE sku_supplier_config(
    sku_id BIGINT PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    purchase_price DECIMAL(18,4) NOT NULL,
    moq INT NOT NULL,
    lead_time_days INT NOT NULL,
    enabled BOOLEAN NOT NULL
);
CREATE TABLE procurement_suggestion(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_no VARCHAR(50) UNIQUE NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    confirmed_by BIGINT,
    confirmed_at TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE procurement_suggestion_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    shortage_quantity INT NOT NULL,
    suggested_quantity INT NOT NULL,
    confirmed_quantity INT,
    purchase_price DECIMAL(18,4) NOT NULL,
    expected_arrival_date DATE
);
CREATE TABLE shortage_coverage(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_item_id BIGINT NOT NULL,
    suggestion_item_id BIGINT NOT NULL,
    covered_quantity INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE purchase_order(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_no VARCHAR(50) UNIQUE NOT NULL,
    suggestion_id BIGINT UNIQUE NOT NULL,
    supplier_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    total_amount DECIMAL(18,2) NOT NULL,
    expected_arrival_date DATE,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE purchase_order_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    sku_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    received_quantity INT NOT NULL DEFAULT 0,
    purchase_price DECIMAL(18,4) NOT NULL
);
CREATE TABLE inventory_balance(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    actual_quantity INT NOT NULL DEFAULT 0,
    locked_quantity INT NOT NULL DEFAULT 0,
    in_transit_quantity INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    UNIQUE(warehouse_id, sku_id)
);
CREATE TABLE inventory_transaction(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    transaction_type VARCHAR(40) NOT NULL,
    business_type VARCHAR(40) NOT NULL,
    business_no VARCHAR(80) NOT NULL,
    actual_delta INT NOT NULL,
    locked_delta INT NOT NULL,
    transit_delta INT NOT NULL,
    actual_before INT NOT NULL,
    actual_after INT NOT NULL,
    locked_before INT NOT NULL,
    locked_after INT NOT NULL,
    transit_before INT NOT NULL,
    transit_after INT NOT NULL
);

INSERT INTO warehouse VALUES(1, TRUE, TRUE);
INSERT INTO supplier VALUES(201, '供应商一');
INSERT INTO sales_order(id,status,receipt_confirmed_at) VALUES(1,'WAITING_STOCK',CURRENT_TIMESTAMP);
INSERT INTO sales_order_item(id,sales_order_id,line_no,sku_id,quantity,locked_quantity,uncovered_quantity)
VALUES(1,1,1,101,3,0,3);
INSERT INTO sku_supplier_config VALUES(101,201,10.0000,10,7,TRUE);
