DROP TABLE IF EXISTS inventory_transaction;
DROP TABLE IF EXISTS inventory_balance;
DROP TABLE IF EXISTS sku_cost_history;
DROP TABLE IF EXISTS goods_receipt_item;
DROP TABLE IF EXISTS goods_receipt;
DROP TABLE IF EXISTS supplier_payment;
DROP TABLE IF EXISTS purchase_order_item;
DROP TABLE IF EXISTS purchase_order;
DROP TABLE IF EXISTS shortage_coverage;
DROP TABLE IF EXISTS procurement_suggestion_item;
DROP TABLE IF EXISTS procurement_suggestion;
DROP TABLE IF EXISTS sku_supplier_purchase_info;
DROP TABLE IF EXISTS sku_supplier_config;
DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS sales_order_item;
DROP TABLE IF EXISTS sales_order;
DROP TABLE IF EXISTS warehouse;
DROP TABLE IF EXISTS supplier;

CREATE TABLE warehouse(
    id BIGINT PRIMARY KEY,
    is_default BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL
);
CREATE TABLE supplier(
    id BIGINT PRIMARY KEY,
    supplier_name VARCHAR(200) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE sku(
    id BIGINT PRIMARY KEY,
    sku_code VARCHAR(80),
    product_name VARCHAR(200) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    current_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    factory_price DECIMAL(18,4),
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE sales_order(
    id BIGINT PRIMARY KEY,
    order_no VARCHAR(50),
    status VARCHAR(40) NOT NULL,
    receipt_confirmed_at TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE sales_order_item(
    id BIGINT PRIMARY KEY,
    sales_order_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    sku_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    locked_quantity INT NOT NULL DEFAULT 0,
    uncovered_quantity INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE sku_supplier_config(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    purchase_price DECIMAL(18,4) NOT NULL,
    moq INT NOT NULL,
    lead_time_days INT NOT NULL,
    enabled BOOLEAN NOT NULL
);
CREATE TABLE sku_supplier_purchase_info(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_product_config_id BIGINT NOT NULL,
    purchase_price DECIMAL(18,4) NOT NULL,
    moq INT NOT NULL,
    lead_time_days INT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE procurement_suggestion(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_no VARCHAR(50) UNIQUE NOT NULL,
    status VARCHAR(30) NOT NULL,
    system_managed BOOLEAN NOT NULL DEFAULT FALSE,
    review_reason VARCHAR(500),
    manually_edited BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    confirmed_by BIGINT,
    confirmed_at TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE procurement_suggestion_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    shortage_quantity INT NOT NULL,
    suggested_quantity INT NOT NULL,
    confirmed_quantity INT,
    purchase_price DECIMAL(18,4) NOT NULL,
    expected_arrival_date DATE,
    supplier_purchase_info_id BIGINT
);
CREATE TABLE shortage_coverage(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_item_id BIGINT NOT NULL,
    suggestion_item_id BIGINT NOT NULL,
    covered_quantity INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE purchase_order(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_no VARCHAR(50) UNIQUE NOT NULL,
    suggestion_id BIGINT UNIQUE,
    manual_entry BOOLEAN NOT NULL DEFAULT FALSE,
    supplier_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    total_amount DECIMAL(18,2) NOT NULL,
    expected_arrival_date DATE,
    purchase_remark VARCHAR(1000),
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE purchase_order_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    sku_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    received_quantity INT NOT NULL DEFAULT 0,
    purchase_price DECIMAL(18,4) NOT NULL,
    price_source VARCHAR(30),
    supplier_purchase_info_id BIGINT
);
CREATE TABLE supplier_payment(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    payment_method VARCHAR(40),
    payment_remark VARCHAR(500),
    invoice_no VARCHAR(100),
    invoice_date DATE,
    paid_at TIMESTAMP,
    confirmed_by BIGINT
);
CREATE TABLE goods_receipt(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR(50) NOT NULL,
    purchase_order_id BIGINT NOT NULL,
    received_at TIMESTAMP,
    received_by BIGINT,
    status VARCHAR(30) NOT NULL
);
CREATE TABLE goods_receipt_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_receipt_id BIGINT NOT NULL,
    purchase_order_item_id BIGINT NOT NULL,
    accepted_quantity INT NOT NULL,
    rejected_quantity INT NOT NULL DEFAULT 0
);
CREATE TABLE sku_cost_history(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id BIGINT NOT NULL,
    old_cost DECIMAL(18,4),
    new_cost DECIMAL(18,4) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_no VARCHAR(80) NOT NULL,
    effective_at TIMESTAMP,
    operated_by BIGINT
);
CREATE TABLE inventory_balance(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    actual_quantity INT NOT NULL DEFAULT 0,
    locked_quantity INT NOT NULL DEFAULT 0,
    in_transit_quantity INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    UNIQUE(warehouse_id, sku_id)
);
CREATE TABLE inventory_transaction(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL,
    sku_id BIGINT NOT NULL,
    transaction_type VARCHAR(40) NOT NULL,
    business_type VARCHAR(40) NOT NULL,
    business_no VARCHAR(80) NOT NULL,
    actual_delta INT NOT NULL,
    locked_delta INT NOT NULL,
    transit_delta INT NOT NULL,
    actual_before INT NOT NULL,
    actual_after INT NOT NULL,
    locked_before INT NOT NULL,
    locked_after INT NOT NULL,
    transit_before INT NOT NULL,
    transit_after INT NOT NULL
);

INSERT INTO warehouse VALUES(1, TRUE, TRUE);
INSERT INTO sku(id,sku_code,product_name,enabled,current_cost,factory_price) VALUES(101, 'P90-001', 'P90', TRUE,8.0000,10.0000);
INSERT INTO sku(id,sku_code,product_name,enabled,current_cost,factory_price) VALUES(102, 'D51-001', 'D51', TRUE,9.0000,10.0000);
INSERT INTO supplier(id,supplier_name,enabled) VALUES(201, '供应商一',TRUE);
INSERT INTO sales_order(id,order_no,status,receipt_confirmed_at) VALUES(1,'DD20260800001','WAITING_STOCK',CURRENT_TIMESTAMP);
INSERT INTO sales_order_item(id,sales_order_id,line_no,sku_id,quantity,locked_quantity,uncovered_quantity)
VALUES(1,1,1,101,3,0,3);
INSERT INTO sku_supplier_config(id,sku_id,supplier_id,purchase_price,moq,lead_time_days,enabled) VALUES(1,101,201,10.0000,10,7,TRUE);
INSERT INTO sku_supplier_purchase_info(id,supplier_product_config_id,purchase_price,moq,lead_time_days,enabled,updated_at,version) VALUES(1,1,10.0000,10,7,TRUE,CURRENT_TIMESTAMP,0);

ALTER TABLE sku ADD COLUMN sales_minimum_order_quantity INT NOT NULL DEFAULT 1;

DROP TABLE IF EXISTS document_number_sequence;
CREATE TABLE document_number_sequence (document_type VARCHAR(32) NOT NULL, year_month CHAR(6) NOT NULL, current_value INT NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(document_type,year_month), CONSTRAINT ck_document_number_value CHECK(current_value BETWEEN 0 AND 99999));
