DROP TABLE IF EXISTS sku_supplier_config;
DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS product_code_rule;
CREATE TABLE product_code_rule(id BIGINT PRIMARY KEY,category VARCHAR(40),code VARCHAR(20),display_name VARCHAR(100),enabled BOOLEAN,sort_order INT,version INT);
CREATE TABLE sku(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,product_code VARCHAR(80) NOT NULL UNIQUE,code_suffix VARCHAR(255),ean_code VARCHAR(12),sku_code VARCHAR(80),model VARCHAR(100),product_name VARCHAR(200) NOT NULL,color VARCHAR(80),lock_body VARCHAR(80),product_version VARCHAR(80),configuration VARCHAR(1000),product_configuration VARCHAR(500),unit VARCHAR(20),current_cost DECIMAL(18,4),factory_price DECIMAL(18,4),product_remark VARCHAR(500),enabled BOOLEAN,brand_rule_id BIGINT,series_rule_id BIGINT,body_color_rule_id BIGINT,lock_type_rule_id BIGINT,connectivity_rule_id BIGINT,sales_channel_rule_id BIGINT,operating_entity_rule_id BIGINT,language_rule_id BIGINT,product_type VARCHAR(30) DEFAULT 'UNCLASSIFIED', material_type VARCHAR(32) NOT NULL DEFAULT 'FINISHED_PRODUCT',door_model_rule_id BIGINT,security_grade_rule_id BIGINT,base_material_rule_id BIGINT,thickness_rule_id BIGINT,finish_color_rule_id BIGINT,version INT DEFAULT 0);
CREATE TABLE sku_supplier_config(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,sku_id BIGINT,supplier_id BIGINT,purchase_price DECIMAL(18,4),moq INT,lead_time_days INT,enabled BOOLEAN,version INT DEFAULT 0);
INSERT INTO product_code_rule VALUES
(1,'BRAND','BR','STANLEY',TRUE,10,0),(2,'SERIES','P90','P90',TRUE,10,0),(9,'SERIES','P50','P50',TRUE,20,0),
(3,'BODY_COLOR','HGT','红钻铜',TRUE,10,0),(4,'LOCK_TYPE','60','6068',TRUE,10,0),(5,'CONNECTIVITY','W','WiFi',TRUE,10,0),
(11,'DOOR_MODEL','M','单开门',TRUE,10,0),(12,'SECURITY_GRADE','J','甲',TRUE,10,0),(13,'BASE_MATERIAL','3','304不锈钢',TRUE,10,0),(14,'THICKNESS','080','80mm',TRUE,10,0),(15,'FINISH_COLOR','A','花色A',TRUE,10,0),
(6,'SALES_CHANNEL','P','平面',TRUE,10,0),(7,'OPERATING_ENTITY','Z','珠海',TRUE,10,0),(8,'LANGUAGE','E','英文版',TRUE,10,0);
INSERT INTO sku(id,product_code,sku_code,product_name,unit,enabled,version) VALUES(100,'OLD_000100','客户-A','历史产品','件',TRUE,0);

ALTER TABLE sku ADD COLUMN sales_minimum_order_quantity INT NOT NULL DEFAULT 1;
