DROP TABLE IF EXISTS product_image;
DROP TABLE IF EXISTS user_session;
DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  role VARCHAR(20) NOT NULL DEFAULT 'USER'
);
CREATE TABLE user_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE sku (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_code VARCHAR(80) NOT NULL UNIQUE,
  product_name VARCHAR(200) NOT NULL
);
CREATE TABLE product_image (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,
  storage_key VARCHAR(255) NOT NULL UNIQUE,
  original_filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(50) NOT NULL,
  file_size BIGINT NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INT NOT NULL,
  uploaded_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_product_image_product FOREIGN KEY (product_id) REFERENCES sku(id) ON DELETE CASCADE,
  CONSTRAINT uk_product_image_order UNIQUE (product_id, sort_order)
);

INSERT INTO sys_user(id,username,password_hash,display_name,enabled,role) VALUES
  (1,'admin','123','Admin',TRUE,'ADMIN'),
  (2,'finance','123','Finance',TRUE,'FINANCE'),
  (3,'regular-user','123','User',TRUE,'USER');
INSERT INTO sku(id,sku_code,product_name) VALUES (1,'SKU-IMAGE','Product image test');
