DROP TABLE IF EXISTS product_code_rule;
CREATE TABLE product_code_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(40) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    version INT NOT NULL DEFAULT 0
);
