DROP TABLE IF EXISTS after_sales_event;
DROP TABLE IF EXISTS after_sales_replacement_line;
DROP TABLE IF EXISTS after_sales_return_line;
DROP TABLE IF EXISTS after_sales_order;
DROP TABLE IF EXISTS sales_shipment_item;
DROP TABLE IF EXISTS sales_shipment;
DROP TABLE IF EXISTS customer_receipt;
DROP TABLE IF EXISTS sales_invoice;
DROP TABLE IF EXISTS exception_case;
DROP TABLE IF EXISTS shortage_coverage;
DROP TABLE IF EXISTS goods_receipt_item;
DROP TABLE IF EXISTS goods_receipt;
DROP TABLE IF EXISTS supplier_payment;
DROP TABLE IF EXISTS purchase_order_item;
DROP TABLE IF EXISTS purchase_order;
DROP TABLE IF EXISTS procurement_suggestion_item;
DROP TABLE IF EXISTS procurement_suggestion;
DROP TABLE IF EXISTS sales_order_item;
DROP TABLE IF EXISTS sales_order;
DROP TABLE IF EXISTS inventory_locked_allocation;
DROP TABLE IF EXISTS inventory_transaction;
DROP TABLE IF EXISTS inventory_balance;
DROP TABLE IF EXISTS sku_cost_history;
DROP TABLE IF EXISTS customer_contract_price;
DROP TABLE IF EXISTS customer_contract;
DROP TABLE IF EXISTS product_image;
DROP TABLE IF EXISTS sku_supplier_purchase_info;
DROP TABLE IF EXISTS sku_supplier_config;
DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS product_code_rule;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS warehouse;

CREATE TABLE customer(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_name VARCHAR(200) NOT NULL);
CREATE TABLE warehouse(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_code VARCHAR(40) UNIQUE NOT NULL, warehouse_name VARCHAR(100) NOT NULL, is_default BOOLEAN DEFAULT FALSE, enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE supplier(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_code VARCHAR(40) UNIQUE NOT NULL, supplier_name VARCHAR(200) NOT NULL, enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE product_code_rule(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category VARCHAR(40) NOT NULL, code VARCHAR(20) NOT NULL, display_name VARCHAR(100) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, version INT NOT NULL DEFAULT 0);
CREATE TABLE sku(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(80) NOT NULL, business_unique_id VARCHAR(200) UNIQUE, product_type VARCHAR(30) NOT NULL DEFAULT 'UNCLASSIFIED',
    material_type VARCHAR(32) NOT NULL DEFAULT 'FINISHED_PRODUCT', customer_part_number VARCHAR(80), code_suffix VARCHAR(100),
    model VARCHAR(100), product_name VARCHAR(200) NOT NULL, color VARCHAR(80), lock_body VARCHAR(80),
    product_version VARCHAR(80), configuration VARCHAR(1000), product_configuration VARCHAR(500), unit VARCHAR(20) NOT NULL DEFAULT '件',
    sales_minimum_order_quantity INT NOT NULL DEFAULT 1, enabled BOOLEAN NOT NULL DEFAULT TRUE,
    brand_rule_id BIGINT, series_rule_id BIGINT, body_color_rule_id BIGINT, lock_type_rule_id BIGINT,
    connectivity_rule_id BIGINT, sales_channel_rule_id BIGINT, operating_entity_rule_id BIGINT, language_rule_id BIGINT,
    CONSTRAINT fk_test_sku_brand FOREIGN KEY(brand_rule_id) REFERENCES product_code_rule(id),
    CONSTRAINT fk_test_sku_series FOREIGN KEY(series_rule_id) REFERENCES product_code_rule(id),
    CONSTRAINT fk_test_sku_color FOREIGN KEY(body_color_rule_id) REFERENCES product_code_rule(id),
    CONSTRAINT fk_test_sku_lock FOREIGN KEY(lock_type_rule_id) REFERENCES product_code_rule(id),
    CONSTRAINT fk_test_sku_connect FOREIGN KEY(connectivity_rule_id) REFERENCES product_code_rule(id),
    CONSTRAINT fk_test_sku_channel FOREIGN KEY(sales_channel_rule_id) REFERENCES product_code_rule(id),
    CONSTRAINT fk_test_sku_entity FOREIGN KEY(operating_entity_rule_id) REFERENCES product_code_rule(id),
    CONSTRAINT fk_test_sku_language FOREIGN KEY(language_rule_id) REFERENCES product_code_rule(id));
CREATE TABLE sku_supplier_config(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sku_id BIGINT NOT NULL, supplier_id BIGINT NOT NULL, purchase_price DECIMAL(18,4) NULL, moq INT NULL, lead_time_days INT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, FOREIGN KEY(sku_id) REFERENCES sku(id), FOREIGN KEY(supplier_id) REFERENCES supplier(id));
CREATE TABLE sku_supplier_purchase_info(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_product_config_id BIGINT NOT NULL, purchase_price DECIMAL(18,4) NULL, moq INT NULL, lead_time_days INT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, FOREIGN KEY(supplier_product_config_id) REFERENCES sku_supplier_config(id));
CREATE TABLE customer_contract(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL, FOREIGN KEY(customer_id) REFERENCES customer(id));
CREATE TABLE customer_contract_price(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, contract_id BIGINT NOT NULL, sku_id BIGINT NOT NULL, sale_price DECIMAL(18,4), FOREIGN KEY(contract_id) REFERENCES customer_contract(id), FOREIGN KEY(sku_id) REFERENCES sku(id));
CREATE TABLE sales_order(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL, order_no VARCHAR(50), FOREIGN KEY(customer_id) REFERENCES customer(id));
CREATE TABLE sales_order_item(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sales_order_id BIGINT NOT NULL, sku_id BIGINT NOT NULL, FOREIGN KEY(sales_order_id) REFERENCES sales_order(id), FOREIGN KEY(sku_id) REFERENCES sku(id));
CREATE TABLE customer_receipt(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sales_order_id BIGINT NOT NULL, FOREIGN KEY(sales_order_id) REFERENCES sales_order(id));
CREATE TABLE sales_invoice(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sales_order_id BIGINT NOT NULL, FOREIGN KEY(sales_order_id) REFERENCES sales_order(id));
CREATE TABLE exception_case(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sales_order_id BIGINT NOT NULL, FOREIGN KEY(sales_order_id) REFERENCES sales_order(id));
CREATE TABLE sales_shipment(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sales_order_id BIGINT NOT NULL, FOREIGN KEY(sales_order_id) REFERENCES sales_order(id));
CREATE TABLE sales_shipment_item(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sales_shipment_id BIGINT NOT NULL, sales_order_item_id BIGINT NOT NULL, FOREIGN KEY(sales_shipment_id) REFERENCES sales_shipment(id), FOREIGN KEY(sales_order_item_id) REFERENCES sales_order_item(id));
CREATE TABLE after_sales_order(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sales_order_id BIGINT NOT NULL, customer_id BIGINT NOT NULL, FOREIGN KEY(sales_order_id) REFERENCES sales_order(id), FOREIGN KEY(customer_id) REFERENCES customer(id));
CREATE TABLE after_sales_return_line(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, after_sales_order_id BIGINT NOT NULL, sales_order_item_id BIGINT NOT NULL, sku_id BIGINT NOT NULL, FOREIGN KEY(after_sales_order_id) REFERENCES after_sales_order(id), FOREIGN KEY(sales_order_item_id) REFERENCES sales_order_item(id), FOREIGN KEY(sku_id) REFERENCES sku(id));
CREATE TABLE after_sales_replacement_line(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, after_sales_order_id BIGINT NOT NULL, return_line_id BIGINT, sku_id BIGINT NOT NULL, FOREIGN KEY(after_sales_order_id) REFERENCES after_sales_order(id), FOREIGN KEY(return_line_id) REFERENCES after_sales_return_line(id), FOREIGN KEY(sku_id) REFERENCES sku(id));
CREATE TABLE after_sales_event(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, after_sales_order_id BIGINT NOT NULL, FOREIGN KEY(after_sales_order_id) REFERENCES after_sales_order(id));
CREATE TABLE procurement_suggestion(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, suggestion_no VARCHAR(50));
CREATE TABLE procurement_suggestion_item(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, suggestion_id BIGINT NOT NULL, sku_id BIGINT NOT NULL, supplier_id BIGINT NOT NULL, supplier_purchase_info_id BIGINT, FOREIGN KEY(suggestion_id) REFERENCES procurement_suggestion(id), FOREIGN KEY(sku_id) REFERENCES sku(id), FOREIGN KEY(supplier_id) REFERENCES supplier(id), FOREIGN KEY(supplier_purchase_info_id) REFERENCES sku_supplier_purchase_info(id));
CREATE TABLE shortage_coverage(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sales_order_item_id BIGINT NOT NULL, suggestion_item_id BIGINT NOT NULL, FOREIGN KEY(sales_order_item_id) REFERENCES sales_order_item(id), FOREIGN KEY(suggestion_item_id) REFERENCES procurement_suggestion_item(id));
CREATE TABLE purchase_order(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, suggestion_id BIGINT, supplier_id BIGINT NOT NULL, FOREIGN KEY(suggestion_id) REFERENCES procurement_suggestion(id), FOREIGN KEY(supplier_id) REFERENCES supplier(id));
CREATE TABLE purchase_order_item(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, purchase_order_id BIGINT NOT NULL, sku_id BIGINT NOT NULL, supplier_purchase_info_id BIGINT, FOREIGN KEY(purchase_order_id) REFERENCES purchase_order(id), FOREIGN KEY(sku_id) REFERENCES sku(id), FOREIGN KEY(supplier_purchase_info_id) REFERENCES sku_supplier_purchase_info(id));
CREATE TABLE supplier_payment(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, purchase_order_id BIGINT NOT NULL, FOREIGN KEY(purchase_order_id) REFERENCES purchase_order(id));
CREATE TABLE goods_receipt(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, purchase_order_id BIGINT NOT NULL, FOREIGN KEY(purchase_order_id) REFERENCES purchase_order(id));
CREATE TABLE goods_receipt_item(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, goods_receipt_id BIGINT NOT NULL, purchase_order_item_id BIGINT NOT NULL, FOREIGN KEY(goods_receipt_id) REFERENCES goods_receipt(id), FOREIGN KEY(purchase_order_item_id) REFERENCES purchase_order_item(id));
CREATE TABLE inventory_balance(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_id BIGINT NOT NULL, sku_id BIGINT NOT NULL, actual_quantity INT DEFAULT 0, locked_quantity INT DEFAULT 0, in_transit_quantity INT DEFAULT 0, source_supplier_name VARCHAR(200), inventory_remark VARCHAR(500), version INT DEFAULT 0, UNIQUE(warehouse_id,sku_id), FOREIGN KEY(warehouse_id) REFERENCES warehouse(id), FOREIGN KEY(sku_id) REFERENCES sku(id));
CREATE TABLE inventory_locked_allocation(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, inventory_balance_id BIGINT NOT NULL, FOREIGN KEY(inventory_balance_id) REFERENCES inventory_balance(id));
CREATE TABLE inventory_transaction(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sku_id BIGINT NOT NULL, FOREIGN KEY(sku_id) REFERENCES sku(id));
CREATE TABLE sku_cost_history(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sku_id BIGINT NOT NULL, FOREIGN KEY(sku_id) REFERENCES sku(id));
CREATE TABLE product_image(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL, FOREIGN KEY(product_id) REFERENCES sku(id));

INSERT INTO customer(id,customer_name) VALUES(1,'保留客户');
INSERT INTO warehouse(id,warehouse_code,warehouse_name,is_default,enabled) VALUES(1,'WH-DEFAULT','默认仓库',TRUE,TRUE);
INSERT INTO supplier(id,supplier_code,supplier_name,enabled) VALUES(1,'SUP00001','测试供应商',TRUE);
INSERT INTO product_code_rule(id,category,code,display_name,enabled) VALUES
(1,'BRAND','BR','BRAVAT',TRUE),(2,'SERIES','P90','P90',TRUE),(3,'BODY_COLOR','YZH','宇宙黑',TRUE),(4,'LOCK_TYPE','70','7068',TRUE),
(5,'CONNECTIVITY','W','WiFi',TRUE),(6,'SALES_CHANNEL','P','平面',TRUE),(7,'OPERATING_ENTITY','Z','珠海',TRUE),(8,'LANGUAGE','C','中文版',TRUE);
