DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS product_code_rule;
CREATE TABLE product_code_rule(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 category VARCHAR(40) NOT NULL,
 code VARCHAR(20) NOT NULL,
 display_name VARCHAR(100) NOT NULL,
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 sort_order INT NOT NULL DEFAULT 0,
 remark VARCHAR(500),
 version INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(category,code)
);
CREATE TABLE sku(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_code VARCHAR(80) NOT NULL UNIQUE,
 sku_code VARCHAR(80), product_name VARCHAR(200) NOT NULL,
 brand_rule_id BIGINT, series_rule_id BIGINT, body_color_rule_id BIGINT, lock_type_rule_id BIGINT,
 connectivity_rule_id BIGINT, sales_channel_rule_id BIGINT, operating_entity_rule_id BIGINT, language_rule_id BIGINT
);
INSERT INTO product_code_rule(id,category,code,display_name,enabled,sort_order,version) VALUES
(1,'BRAND','BR','STANLEY',TRUE,10,0),(2,'BODY_COLOR','HGT','红钻铜',TRUE,10,0),(3,'LANGUAGE','E','英文版',FALSE,10,0);
INSERT INTO sku(product_code,product_name,brand_rule_id) VALUES('BR_P90HGT60WPZE','测试产品',1);
INSERT INTO sys_user(username,password_hash,display_name,enabled,role) VALUES('writer','123','普通用户',TRUE,'USER');
