DROP TABLE IF EXISTS customer_fund_ledger;
DROP TABLE IF EXISTS customer_fund_request;
DROP TABLE IF EXISTS customer_fund_account;

CREATE TABLE customer_fund_account (
    customer_id BIGINT PRIMARY KEY,
    balance DECIMAL(19,4) NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE customer_fund_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    request_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    amount DECIMAL(19,4) NOT NULL
);
CREATE TABLE customer_fund_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    entry_type VARCHAR(30) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    amount DECIMAL(19,4) NOT NULL,
    balance_before DECIMAL(19,4) NOT NULL,
    balance_after DECIMAL(19,4) NOT NULL
);

INSERT INTO customer_fund_account(customer_id,balance,version) VALUES(1,123.4500,0);
INSERT INTO customer_fund_request(customer_id,request_type,status,amount)
VALUES(1,'RECEIPT','APPROVED',10.0000);
INSERT INTO customer_fund_ledger(customer_id,entry_type,direction,amount,balance_before,balance_after)
VALUES(1,'RECEIPT','CREDIT',10.0000,113.4500,123.4500);
