DROP TABLE IF EXISTS sku_supplier_purchase_info;
DROP TABLE IF EXISTS sku_supplier_config;
DROP TABLE IF EXISTS sku;
DROP TABLE IF EXISTS supplier;

CREATE TABLE supplier(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code VARCHAR(40) NOT NULL UNIQUE,
    supplier_name VARCHAR(200) NOT NULL,
    contact_name VARCHAR(100),
    phone VARCHAR(40),
    bank_account VARCHAR(120),
    manufacturer_category VARCHAR(100),
    manufacturer_type VARCHAR(100),
    supplier_location VARCHAR(100),
    product_attribute VARCHAR(100),
    short_name VARCHAR(120),
    contact_title VARCHAR(100),
    address VARCHAR(500),
    currency VARCHAR(100),
    tax_registration_no VARCHAR(100),
    bank_address VARCHAR(500),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);
CREATE TABLE sku(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_code VARCHAR(80),
    model VARCHAR(100),
    product_name VARCHAR(200) NOT NULL,
    configuration VARCHAR(1000),
    unit VARCHAR(20) NOT NULL DEFAULT '件',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE sku_supplier_config(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    purchase_price DECIMAL(18,4) NOT NULL,
    moq INT NOT NULL,
    lead_time_days INT NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);

CREATE TABLE sku_supplier_purchase_info(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_product_config_id BIGINT NOT NULL,
    purchase_price DECIMAL(18,4) NOT NULL,
    moq INT NOT NULL,
    lead_time_days INT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0
);
INSERT INTO supplier(id,supplier_code,supplier_name,contact_name,phone,bank_account,updated_at,version)
VALUES(201,'SUP-201','贝朗供应商','张三','13800138000','6222-201',TIMESTAMP '2026-08-06 10:00:00',0);
INSERT INTO supplier(id,supplier_code,supplier_name,enabled,updated_at,version)
VALUES(202,'SUP-202','Disabled legacy supplier',FALSE,TIMESTAMP '2026-08-06 10:00:00',0);
INSERT INTO sku(id,sku_code,model,product_name,configuration,unit,updated_at)
VALUES(101,'P90-001','P90','P90 智能锁','可视对讲','件',TIMESTAMP '2026-08-06 09:00:00');
INSERT INTO sku_supplier_config(id,sku_id,supplier_id,purchase_price,moq,lead_time_days,enabled,version)
VALUES(1,101,201,220.0000,5,7,TRUE,0);
INSERT INTO sku_supplier_purchase_info(id,supplier_product_config_id,purchase_price,moq,lead_time_days,enabled,updated_at,version)
VALUES(1,1,220.0000,5,7,TRUE,TIMESTAMP '2026-08-06 10:00:00',0);

ALTER TABLE sku ADD COLUMN sales_minimum_order_quantity INT NOT NULL DEFAULT 1;
