<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import ChineseDatePicker from './ChineseDatePicker.vue'
import OverflowText from './OverflowText.vue'
import { loadOrderSkus, type OrderSku } from '../api/workbench'
import { createAfterSales, loadAfterSalesOrderLines, loadAfterSalesOrderOptions, updateAfterSales, type AfterSalesDetail, type AfterSalesOrderLine, type AfterSalesOrderOption } from '../api/after-sales'

const props=defineProps<{ detail?:AfterSalesDetail }>()
const emit=defineEmits<{close:[];saved:[];message:[text:string,kind?:'success'|'error']}>()
const orders=ref<AfterSalesOrderOption[]>([]),orderLines=ref<AfterSalesOrderLine[]>([]),skus=ref<OrderSku[]>([]),saving=ref(false)
const form=reactive({orderId:props.detail?.salesOrderId??0,applicationDate:props.detail?.applicationDate??new Date().toISOString().slice(0,10),issueDescription:props.detail?.issueDescription??'',contactName:props.detail?.contactName??'',contactPhone:props.detail?.contactPhone??'',deliveryAddress:props.detail?.deliveryAddress??'',remark:props.detail?.remark??'',returns:[] as {selected:boolean;line:AfterSalesOrderLine;quantity:number;replacementSkuId:number;replacementQuantity:number}[]})
const editable=!props.detail||props.detail.status==='WAITING_RETURN'
async function chooseOrder(){if(!form.orderId)return;orderLines.value=await loadAfterSalesOrderLines(form.orderId);form.returns=orderLines.value.map(line=>({selected:false,line,quantity:1,replacementSkuId:0,replacementQuantity:1}))}
onMounted(async()=>{[orders.value,skus.value]=await Promise.all([loadAfterSalesOrderOptions(),loadOrderSkus()]);if(props.detail){orderLines.value=props.detail.returnLines;form.returns=props.detail.returnLines.map(line=>{const replacement=props.detail!.replacementLines.find(item=>item.returnLineId===line.id);return{selected:true,line,quantity:line.requestedQuantity,replacementSkuId:replacement?.skuId??0,replacementQuantity:replacement?.plannedQuantity??1}})}else if(form.orderId)await chooseOrder()})
watch(()=>form.orderId,()=>{if(!props.detail)chooseOrder()})
async function save(){const selected=form.returns.filter(item=>item.selected);if(!form.orderId||!selected.length){emit('message','请选择订单和至少一条退货明细','error');return}if(!form.issueDescription.trim()){emit('message','请填写问题描述','error');return}if(selected.some(item=>item.quantity<=0||item.quantity>item.line.availableReturnQuantity)){emit('message','退回数量必须大于零且不能超过可退数量','error');return}const data={orderId:form.orderId,applicationDate:form.applicationDate,issueDescription:form.issueDescription,contactName:form.contactName,contactPhone:form.contactPhone,deliveryAddress:form.deliveryAddress,remark:form.remark,version:props.detail?.version,returnLines:selected.map(item=>({salesOrderItemId:item.line.salesOrderItemId,requestedQuantity:item.quantity})),replacementLines:selected.filter(item=>item.replacementSkuId>0).map(item=>({salesOrderItemId:item.line.salesOrderItemId,skuId:item.replacementSkuId,plannedQuantity:item.replacementQuantity}))};saving.value=true;try{props.detail?await updateAfterSales(props.detail.id,data):await createAfterSales(data);emit('saved')}catch(e){emit('message',e instanceof Error?e.message:'保存失败','error')}finally{saving.value=false}}
</script>
<template><div class="dialog-mask"><section class="dialog-card after-sales-dialog" role="dialog" aria-modal="true"><header><div><h2>{{detail?'修改售后':'新增售后'}}</h2><p>关联原订单，登记退货与跨商品换货</p></div><button @click="emit('close')">关闭</button></header><div class="after-sales-body"><section class="order-section"><h3>基本信息</h3><div class="form-grid after-sales-basic"><label><span>原销售订单</span><select v-model.number="form.orderId" :disabled="!!detail"><option :value="0">请选择订单</option><option v-for="o in orders" :key="o.id" :value="o.id">{{o.orderNo}} · {{o.customerName}}</option></select></label><label><span>申请日期</span><ChineseDatePicker v-model="form.applicationDate" :disabled="!editable" /></label><label class="wide-field"><span>问题描述</span><textarea v-model="form.issueDescription" :readonly="!editable" rows="3" /></label><label><span>联系人</span><input v-model="form.contactName" :readonly="!editable"></label><label><span>联系电话</span><input v-model="form.contactPhone" :readonly="!editable"></label><label class="wide-field"><span>收货地址</span><input v-model="form.deliveryAddress" :readonly="!editable"></label><label class="wide-field"><span>备注</span><textarea v-model="form.remark" :readonly="!editable" rows="2" /></label></div></section><section class="order-section"><h3>退货与换货明细</h3><div class="after-sales-lines"><div class="after-sales-line-head"><span>选择</span><span>原商品</span><span>已发/可退</span><span>退回数量</span><span>换出商品（可不同）</span><span>换出数量</span></div><div v-for="item in form.returns" :key="item.line.salesOrderItemId" class="after-sales-line"><input v-model="item.selected" type="checkbox" :disabled="!editable"><div><strong><OverflowText :value="item.line.skuCode" /></strong><small><OverflowText :value="`${item.line.productName??''} ${item.line.configuration??''}`" /></small></div><span>{{item.line.shippedQuantity}} / {{item.line.availableReturnQuantity}}</span><input v-model.number="item.quantity" type="number" min="1" :max="item.line.availableReturnQuantity" :disabled="!editable||!item.selected"><select v-model.number="item.replacementSkuId" :disabled="!editable||!item.selected"><option :value="0">仅退货</option><option v-for="sku in skus" :key="sku.id" :value="sku.id">{{sku.skuCode}} · {{sku.productName}}</option></select><input v-model.number="item.replacementQuantity" type="number" min="1" :disabled="!editable||!item.selected||!item.replacementSkuId"></div><p v-if="!form.returns.length" class="trace-empty">所选订单暂无可售后商品</p></div></section></div><footer class="dialog-actions"><button class="secondary-action" @click="emit('close')">取消操作</button><button v-if="editable" class="primary-action" :disabled="saving" @click="save">{{saving?'正在保存':'确认保存'}}</button></footer></section></div></template>
