<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import type { UserRole } from '../api/auth'
import { canReviewCustomerFunds, loadCustomerFundLedger, loadCustomerFundOrders, loadCustomerFundOverview, loadCustomerFundRequests, loadCustomerFundSummary, reviewCustomerFundRequest, submitCustomerDeposit, type FundLedger, type FundOrderOption, type FundOverview, type FundRequest, type FundSummary } from '../api/customer-funds'
import FuzzyPicker, { type FuzzyPickerOption } from './FuzzyPicker.vue'
const props=defineProps<{customer:Record<string,unknown>;currentUserRole:UserRole}>()
const emit=defineEmits<{close:[];changed:[];message:[text:string,kind?:'success'|'error']}>()
const overview=ref<FundOverview>();const requests=ref<FundRequest[]>([]);const ledger=ref<FundLedger[]>([]);const summary=ref<FundSummary[]>([]);const orders=ref<FundOrderOption[]>([]);const loading=ref(true);const error=ref('');const tab=ref<'requests'|'ledger'|'summary'>('requests');const saving=ref(false)
const dialog=ref<HTMLElement>()
const form=reactive<{amount:string;paymentDate:string;paymentMethod:string;referenceNo:string;remark:string;orderId:number|null}>({amount:'',paymentDate:new Date().toISOString().slice(0,10),paymentMethod:'银行转账',referenceNo:'',remark:'',orderId:null})
const customerId=computed(()=>Number(props.customer.id));const canReview=computed(()=>canReviewCustomerFunds(props.currentUserRole))
const orderOptions=computed<FuzzyPickerOption[]>(()=>orders.value.map(order=>({id:order.id,label:[order.orderNo,order.orderDate,order.status].filter(Boolean).join(' · '),searchText:order.orderNo})))
const money=(v:unknown)=>Number(v??0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})
const requestType=(v:string)=>({CUSTOMER_DEPOSIT:'客户打款',AFTER_SALES_REFUND:'售后退款'}[v]??v)
const status=(v:string)=>({PENDING:'待审核',APPROVED:'已通过',REJECTED:'已拒绝',REVERSED:'已冲正'}[v]??v)
const entryType=(v:string)=>({CUSTOMER_DEPOSIT:'客户打款',ORDER_RECEIPT:'订单收款扣减',AFTER_SALES_REFUND:'售后退款',REVERSAL:'冲正'}[v]??v)
async function load(){loading.value=true;error.value='';try{[overview.value,requests.value,ledger.value,summary.value,orders.value]=await Promise.all([loadCustomerFundOverview(customerId.value),loadCustomerFundRequests(customerId.value),loadCustomerFundLedger(customerId.value),loadCustomerFundSummary(customerId.value),loadCustomerFundOrders(customerId.value)])}catch(cause){error.value=cause instanceof Error?cause.message:'读取客户资金失败'}finally{loading.value=false}}
async function deposit(){const amount=Number(form.amount);if(!Number.isFinite(amount)||amount<=0){error.value='打款金额必须大于 0';return}if(!form.paymentDate||!form.paymentMethod.trim()){error.value='请填写打款日期和方式';return}saving.value=true;try{await submitCustomerDeposit(customerId.value,{amount,paymentDate:form.paymentDate,paymentMethod:form.paymentMethod.trim(),referenceNo:form.referenceNo.trim()||undefined,remark:form.remark.trim()||undefined,orderId:form.orderId??undefined});form.amount='';form.referenceNo='';form.remark='';form.orderId=null;dialog.value?.dispatchEvent(new CustomEvent('dialog-clean',{bubbles:true}));emit('message','打款记录已提交，等待审核');emit('changed');await load()}catch(cause){error.value=cause instanceof Error?cause.message:'提交失败'}finally{saving.value=false}}
async function review(id:number,approved:boolean){saving.value=true;try{await reviewCustomerFundRequest(id,approved,'');emit('message',approved?'审核通过并已入账':'记录已拒绝');emit('changed');await load()}catch(cause){error.value=cause instanceof Error?cause.message:'审核失败'}finally{saving.value=false}}
onMounted(load)
</script>
<template>
<div class="dialog-mask"><section ref="dialog" class="dialog-card customer-funds-dialog" role="dialog" aria-modal="true"><header><div><h2>客户资金管理</h2><p>{{ customer.customerName }}</p></div><button type="button" :disabled="saving" @click="emit('close')">关闭</button></header>
<div class="customer-funds-body"><p v-if="loading">正在读取资金数据…</p><template v-else>
<div class="fund-overview"><div><span>可用余额</span><strong>¥ {{ money(overview?.balance) }}</strong></div><div><span>订单未收金额</span><strong>¥ {{ money(overview?.orderOutstandingAmount) }}</strong></div><div><span>余额覆盖比例</span><strong :class="{danger:overview?.insufficient}">{{ money(overview?.coverageRatio) }}%</strong></div><div><span>待审核金额</span><strong>¥ {{ money(overview?.pendingAmount) }}</strong></div></div>
<p v-if="overview?.insufficient" class="fund-warning">余额不足，请关注后续打款；该提示仅供查看和业务判断。</p>
<form class="fund-deposit" @submit.prevent="deposit"><label><span>本次打款</span><input v-model="form.amount" type="number" min="0.01" step="0.01"></label><label><span>打款日期</span><input v-model="form.paymentDate" type="date"></label><label><span>打款方式</span><input v-model="form.paymentMethod"></label><label><span>银行流水号</span><input v-model="form.referenceNo"></label><label class="fund-order-field"><span>关联订单号（选填）</span><FuzzyPicker data-test="fund-order-picker" v-model="form.orderId" :options="orderOptions" placeholder="搜索当前客户订单号；预付款可不选" empty-text="当前客户没有可关联订单" :disabled="saving" /></label><label class="fund-remark"><span>备注</span><input v-model="form.remark"></label><button class="primary-action" :disabled="saving">提交审核</button></form>
<nav class="fund-tabs"><button :class="{active:tab==='requests'}" @click="tab='requests'">打款与审核</button><button :class="{active:tab==='ledger'}" @click="tab='ledger'">资金流水</button><button :class="{active:tab==='summary'}" @click="tab='summary'">月度汇总</button></nav>
<div class="fund-table-wrap"><table v-if="tab==='requests'"><thead><tr><th>类型</th><th>金额</th><th>状态</th><th>时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in requests" :key="item.id"><td>{{ requestType(item.requestType) }}</td><td>¥ {{ money(item.amount) }}</td><td>{{ status(item.status) }}</td><td>{{ item.submittedAt||'—' }}</td><td><template v-if="item.status==='PENDING'&&canReview"><button data-test="fund-review-approve" :disabled="saving" @click="review(item.id,true)">通过</button><button :disabled="saving" @click="review(item.id,false)">拒绝</button></template><span v-else>—</span></td></tr></tbody></table>
<table v-else-if="tab==='ledger'"><thead><tr><th>类型</th><th>变动</th><th>变动后余额</th><th>业务单号</th><th>操作时间</th></tr></thead><tbody><tr v-for="item in ledger" :key="item.id"><td>{{ entryType(item.entryType) }}</td><td :class="{danger:item.direction==='OUT'}">{{ item.direction==='IN'?'+':'-' }} ¥ {{ money(item.amount) }}</td><td>¥ {{ money(item.balanceAfter) }}</td><td>{{ item.sourceNo||'—' }}</td><td>{{ item.operatedAt||'—' }}</td></tr></tbody></table>
<table v-else><thead><tr><th>月份</th><th>客户打款</th><th>订单扣减</th><th>售后退款</th><th>净变动</th><th>期末余额</th></tr></thead><tbody><tr v-for="item in summary" :key="item.period"><td>{{ item.period }}</td><td>¥ {{ money(item.depositAmount) }}</td><td>¥ {{ money(item.receiptAmount) }}</td><td>¥ {{ money(item.refundAmount) }}</td><td>¥ {{ money(item.netChange) }}</td><td>¥ {{ money(item.closingBalance) }}</td></tr></tbody></table></div></template>
<p v-if="error" class="form-error" role="alert">{{ error }}</p></div></section></div>
</template>