<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { createCustomer, getCustomer, loadOrderSkus, updateCustomer, type CustomerCommand, type CustomerContract, type OrderSku } from '../api/workbench'
import ChineseDatePicker from './ChineseDatePicker.vue'
import FuzzyPicker, { type FuzzyPickerOption } from './FuzzyPicker.vue'

const props=defineProps<{row?:Record<string,unknown>}>()
const emit=defineEmits<{close:[];saved:[];message:[text:string,kind?:'success'|'error']}>()
const form=reactive({customerCode:'',customerType:'DOMESTIC' as 'DOMESTIC'|'EXPORT',customerName:'',address:'',businessContactName:'',businessContactPhone:'',orderContactName:'',orderContactPhone:'',financeContactName:'',financeContactPhone:'',invoiceTitle:'',taxpayerId:'',invoiceAddress:'',invoicePhone:'',bankName:'',bankAccount:''})
const contracts=ref<CustomerContract[]>([]);const skus=ref<OrderSku[]>([]);const picks=ref<(number|null)[]>([]);const version=ref<number>();const loading=ref(true);const saving=ref(false);const error=ref('')
const skuOptions=computed<FuzzyPickerOption[]>(()=>skus.value.map(s=>({id:s.id,label:[s.skuCode,s.productName].filter(Boolean).join(' · ')||`产品 ${s.id}`,searchText:[s.skuCode,s.productName,s.model,s.configuration].filter(Boolean).join(' ')})))
const generatedCustomerCode=computed(()=>{const taxpayerId=form.taxpayerId.trim().toUpperCase();return taxpayerId.length<10?'':`${form.customerType==='DOMESTIC'?'A.':'B.'}${taxpayerId.slice(-10)}`})
function addContract(){contracts.value.push({contractNo:'',startDate:'',endDate:'',remark:'',prices:[]});picks.value.push(null)}
function removeContract(index:number){contracts.value.splice(index,1);picks.value.splice(index,1)}
function addProduct(index:number){const skuId=picks.value[index];if(!skuId||contracts.value[index].prices.some(p=>p.skuId===skuId))return;const sku=skus.value.find(s=>s.id===skuId);contracts.value[index].prices.push({skuId,salePrice:0,skuCode:sku?.skuCode??'',productName:sku?.productName??''});picks.value[index]=null}
function removeProduct(contractIndex:number,priceIndex:number){contracts.value[contractIndex].prices.splice(priceIndex,1)}
function label(price:{skuId:number;skuCode?:string;productName?:string}){const sku=skus.value.find(s=>s.id===price.skuId);return [sku?.skuCode??price.skuCode,sku?.productName??price.productName].filter(Boolean).join(' · ')||`产品 ${price.skuId}`}
function payload():CustomerCommand{return {...form,contracts:contracts.value.map(c=>({contractNo:c.contractNo.trim(),startDate:c.startDate,endDate:c.endDate,remark:c.remark?.trim(),prices:c.prices.map(p=>({skuId:p.skuId,salePrice:Number(p.salePrice)}))})),version:version.value}}
async function save(){error.value='';if(!form.customerName.trim()){error.value='请填写客户名称';return}if(form.taxpayerId.trim().length<10){error.value='纳税人识别号至少需要10位';return}if(contracts.value.some(c=>!c.contractNo.trim()||!c.startDate||!c.endDate||c.endDate<c.startDate)){error.value='请完整填写正确的合同编号和有效期';return}saving.value=true;try{if(props.row?.id)await updateCustomer(Number(props.row.id),payload());else await createCustomer(payload());emit('message',props.row?.id?'客户已修改':'客户已新增');emit('saved')}catch(e){error.value=e instanceof Error?e.message:'保存客户失败'}finally{saving.value=false}}
async function initialise(){try{skus.value=await loadOrderSkus();if(!props.row?.id)return;const d=await getCustomer(Number(props.row.id));Object.keys(form).forEach(k=>(form as Record<string,string>)[k]=String(d[k]??''));version.value=Number(d.version);contracts.value=Array.isArray(d.contracts)?(d.contracts as CustomerContract[]).map(c=>({...c,startDate:String(c.startDate).slice(0,10),endDate:String(c.endDate).slice(0,10),prices:c.prices.map(p=>({...p,salePrice:Number(p.salePrice)}))})):[];picks.value=contracts.value.map(()=>null)}catch(e){error.value=e instanceof Error?e.message:'读取客户资料失败'}finally{loading.value=false}}
onMounted(initialise)
</script>
<template><div class="dialog-mask"><section class="dialog-card supplier-dialog customer-dialog" role="dialog"><header><h2>{{row?.id?'修改客户':'新增客户'}}</h2><button type="button" @click="emit('close')">关闭</button></header><form @submit.prevent="save">
<section class="order-section"><h3>基本资料</h3><div class="form-grid"><label><span>客户类型</span><select data-test="customer-type" v-model="form.customerType" required><option value="DOMESTIC">内销客户</option><option value="EXPORT">外销客户</option></select></label><label><span>客户编码</span><input data-test="customer-code" :value="generatedCustomerCode" readonly placeholder="选择客户类型并填写纳税号后自动生成"></label><label><span>客户名称</span><input data-test="customer-name" v-model="form.customerName" required></label><label class="wide-field"><span>客户地址</span><textarea v-model="form.address"></textarea></label></div></section>
<section class="order-section"><h3>联系人</h3><div class="form-grid"><label><span>业务联系人</span><input v-model="form.businessContactName"></label><label><span>业务电话</span><input v-model="form.businessContactPhone"></label><label><span>订单联系人</span><input v-model="form.orderContactName"></label><label><span>订单电话</span><input v-model="form.orderContactPhone"></label><label><span>财务联系人</span><input v-model="form.financeContactName"></label><label><span>财务电话</span><input v-model="form.financeContactPhone"></label></div></section>
<section class="order-section"><h3>开票信息</h3><div class="form-grid"><label><span>发票抬头</span><input v-model="form.invoiceTitle"></label><label><span>纳税人识别号</span><input data-test="taxpayer-id" v-model="form.taxpayerId" required></label><label><span>开票地址</span><input v-model="form.invoiceAddress"></label><label><span>开票电话</span><input v-model="form.invoicePhone"></label><label><span>开户银行</span><input v-model="form.bankName"></label><label><span>银行账号</span><input v-model="form.bankAccount"></label></div></section>
<section class="supplier-products-section"><div class="supplier-products-heading"><div><h3>客户合同与固定价格</h3><p>合同有效期内，订单选择对应产品时自动带入这里的含税价格。</p></div><button data-test="add-contract" type="button" class="secondary-action" @click="addContract">新增合同</button></div>
<article v-for="(contract,ci) in contracts" :key="ci" class="customer-contract-card"><div class="customer-contract-header"><div class="customer-contract-title"><span class="customer-contract-number">{{ci+1}}</span><h3>合同 {{ci+1}}</h3></div><button type="button" class="customer-contract-remove" @click="removeContract(ci)">删除合同</button></div><div class="form-grid customer-contract-fields"><label><span>合同编号</span><input :data-test="`contract-no-${ci}`" v-model="contract.contractNo" placeholder="请输入合同编号"></label><label><span>开始日期</span><ChineseDatePicker :data-test="`contract-start-${ci}`" v-model="contract.startDate" placeholder="请选择开始日期"/></label><label><span>结束日期</span><ChineseDatePicker :data-test="`contract-end-${ci}`" v-model="contract.endDate" placeholder="请选择结束日期"/></label><label><span>备注</span><input v-model="contract.remark" placeholder="选填"></label></div>
<div class="contract-product-toolbar" :data-test="`contract-product-toolbar-${ci}`"><div class="contract-product-picker"><span>添加合同产品</span><FuzzyPicker :data-test="`contract-product-picker-${ci}`" v-model="picks[ci]" :options="skuOptions" placeholder="搜索物料编号、型号或产品名称"/></div><button :data-test="`add-contract-product-${ci}`" type="button" class="contract-add-product-button" :disabled="picks[ci] == null" @click="addProduct(ci)"><span aria-hidden="true">＋</span>添加至合同</button></div>
<div v-if="contract.prices.length" class="supplier-products-table-wrap"><table class="supplier-products-table"><thead><tr><th>产品</th><th>固定含税价格</th><th>操作</th></tr></thead><tbody><tr v-for="(price,pi) in contract.prices" :key="price.skuId"><td>{{label(price)}}</td><td><input :data-test="`contract-price-${ci}-${pi}`" v-model.number="price.salePrice" type="number" min="0" step="0.0001"></td><td><button type="button" @click="removeProduct(ci,pi)">删除</button></td></tr></tbody></table></div></article>
<p v-if="!contracts.length" class="supplier-products-empty">尚未设置合同；历史客户仍可下单，新增合同后将按有效期管理。</p></section>
<p v-if="error" class="form-error">{{error}}</p><footer><button type="button" @click="emit('close')">取消操作</button><button class="primary-action" :disabled="loading||saving">确认保存</button></footer></form></section></div></template>
