<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { createOrder, loadOrderCustomers, loadOrderSkus, type OrderCustomer, type OrderSku, updateOrder } from '../api/workbench'
import ChineseDatePicker from './ChineseDatePicker.vue'

interface Line { lineNo?:number; skuId:number|null; quantity:number; salePrice:number; shippedQuantity?:number; remainingQuantity?:number }
const props=defineProps<{row?:Record<string,unknown>;defaultSalesperson?:string}>()
const emit=defineEmits<{close:[];saved:[];message:[text:string,kind?:'success'|'error']}>()
const today=new Date().toISOString().slice(0,10)
const form=reactive({customerId:Number(props.row?.customerId)||null,externalOrderNo:String(props.row?.externalOrderNo??''),orderDate:String(props.row?.orderDate??today).slice(0,10),orderType:String(props.row?.orderType??'工程订单'),status:String(props.row?.status??'PENDING_CUSTOMER_PAYMENT'),salesperson:String(props.row?.salesperson??props.defaultSalesperson??''),customerContact:String(props.row?.customerContact??''),customerPhone:String(props.row?.customerPhone??''),remark:String(props.row?.remark??''),deliveryAddress:String(props.row?.deliveryAddress??''),deliveryContact:String(props.row?.deliveryContact??''),deliveryPhone:String(props.row?.deliveryPhone??''),shippingMethod:String(props.row?.shippingMethod??''),version:props.row?.version as number|undefined,items:(props.row?.items as Line[]|undefined)?.map(x=>({...x}))??[{skuId:null,quantity:1,salePrice:0}]})
const skus=ref<OrderSku[]>([]);const customers=ref<OrderCustomer[]>([]);const saving=ref(false);const error=ref('');const isEditing=computed(()=>Boolean(props.row?.id))
function skuFor(line:Line){return skus.value.find(s=>s.id===line.skuId)}
function skuLabel(sku:OrderSku){const code=String(sku.skuCode??'').trim();if(code)return code;const details=[sku.model,sku.productName,sku.configuration].map(value=>String(value??'').trim()).filter(Boolean);return [...new Set(details)].join(' · ')||('未编号物料 #' + sku.id)}
function selectCustomer(){const c=customers.value.find(item=>item.id===form.customerId);if(!c)return;if(!form.customerContact)form.customerContact=c.contactName??'';if(!form.customerPhone)form.customerPhone=c.phone??'';if(!form.deliveryAddress)form.deliveryAddress=c.address??''}
function add(){form.items.push({skuId:null,quantity:1,salePrice:0})}function remove(index:number){if(form.items.length>1)form.items.splice(index,1)}function lineNo(index:number){return form.items[index].lineNo??(index+1)*10000}
function validationMessage(){if(!form.customerId)return '请选择客户';if(!form.orderDate)return '请选择订单日期';if(!form.orderType.trim())return '请填写订单类型';if(!form.salesperson.trim())return '请填写销售员';const invalidSku=form.items.findIndex(line=>!line.skuId);if(invalidSku>=0)return `请选择第 ${invalidSku+1} 条明细的物料编号`;const invalidQuantity=form.items.findIndex(line=>!Number.isFinite(line.quantity)||line.quantity<=0);if(invalidQuantity>=0)return `第 ${invalidQuantity+1} 条明细的订单数量必须大于 0`;const invalidPrice=form.items.findIndex(line=>!Number.isFinite(line.salePrice)||line.salePrice<0);if(invalidPrice>=0)return `第 ${invalidPrice+1} 条明细的含税单价不能小于 0`;return ''}
function hasError(message:string){return error.value===message}
function lineError(index:number,field:'sku'|'quantity'|'price'){const number=index+1;if(field==='sku')return hasError(`请选择第 ${number} 条明细的物料编号`);if(field==='quantity')return hasError(`第 ${number} 条明细的订单数量必须大于 0`);return hasError(`第 ${number} 条明细的含税单价不能小于 0`)}
async function save(){error.value=validationMessage();if(error.value){emit('message',error.value,'error');return}saving.value=true;try{const payload={...form,items:form.items.map((line,index)=>({lineNo:lineNo(index),skuId:line.skuId,quantity:line.quantity,salePrice:line.salePrice}))};if(props.row?.id)await updateOrder(Number(props.row.id),payload);else await createOrder(payload);emit('message','订单保存成功');emit('saved')}catch(e){error.value=e instanceof Error?e.message:'订单保存失败';emit('message',error.value,'error')}finally{saving.value=false}}
onMounted(async()=>{try{[skus.value,customers.value]=await Promise.all([loadOrderSkus(),loadOrderCustomers()])}catch(e){emit('message',e instanceof Error?e.message:'无法加载订单基础数据','error')}})
</script>
<template><div class="dialog-mask" @click.self="emit('close')"><section class="dialog-card order-dialog" role="dialog"><header><h2>{{isEditing?'修改订单':'新增订单'}}</h2><button @click="emit('close')">关闭</button></header><form novalidate @submit.prevent="save">
<section class="order-section"><h3>基本信息</h3><div class="form-grid order-basic"><label><span>订单编号</span><input :value="String(row?.orderNo??'保存后自动生成')" disabled></label><label :class="{'field-invalid':hasError('请选择订单日期')}"><span>订单日期 <small v-if="hasError('请选择订单日期')" class="field-error">请选择订单日期</small></span><ChineseDatePicker v-model="form.orderDate" placeholder="请选择订单日期" /></label><label :class="{'field-invalid':hasError('请填写订单类型')}"><span>订单类型 <small v-if="hasError('请填写订单类型')" class="field-error">请填写订单类型</small></span><input v-model.trim="form.orderType"></label><label><span>订单状态</span><select v-model="form.status"><option value="DRAFT">草稿</option><option value="PENDING_CUSTOMER_PAYMENT">确认订单并分配库存</option></select></label><label :class="{'field-invalid':hasError('请填写销售员')}"><span>销售员 <small v-if="hasError('请填写销售员')" class="field-error">请填写销售员</small></span><input v-model.trim="form.salesperson"></label></div></section>
<section class="order-section"><h3>客户信息</h3><div class="form-grid"><label :class="{'field-invalid':hasError('请选择客户')}"><span>客户 <small v-if="hasError('请选择客户')" data-test="customer-error" class="field-error">请选择客户</small></span><select v-model.number="form.customerId" @change="selectCustomer"><option :value="null" disabled>请选择客户</option><option v-for="customer in customers" :key="customer.id" :value="customer.id">{{customer.customerName}}</option></select></label><label><span>客户联系人</span><input v-model.trim="form.customerContact"></label><label><span>客户电话</span><input v-model.trim="form.customerPhone"></label><label class="wide-field"><span>备注</span><textarea v-model.trim="form.remark"></textarea></label></div></section>
<section class="order-section"><h3>收货信息</h3><div class="form-grid"><label class="wide-field"><span>收货地址</span><textarea v-model.trim="form.deliveryAddress"></textarea></label><label><span>收货联系人</span><input v-model.trim="form.deliveryContact"></label><label><span>收货联系电话</span><input v-model.trim="form.deliveryPhone"></label><label><span>发货方式</span><input v-model.trim="form.shippingMethod" placeholder="例如：物流、快递"></label></div></section>
<section class="order-section"><div class="line-title"><h3>订单明细</h3><button type="button" @click="add">新增明细</button></div><p v-if="!skus.length" class="empty-option-hint">暂无可选物料，请先导入产品或库存数据。</p><div class="order-lines-scroll" data-test="order-lines-scroll"><div class="order-lines"><div v-for="(line,index) in form.items" :key="index" class="order-line order-line-full"><span class="line-number">{{index+1}}</span><label :class="{'field-invalid':lineError(index,'sku')}"><span>物料编号 <small v-if="lineError(index,'sku')" class="field-error">请选择物料</small></span><select v-model.number="line.skuId"><option :value="null" disabled>{{skus.length?'请选择物料':'暂无可选物料，请先导入产品或库存'}}</option><option v-for="sku in skus" :key="sku.id" :value="sku.id">{{skuLabel(sku)}}</option></select></label><label><span>物料名称</span><input :value="skuFor(line)?.productName??''" disabled></label><label><span>规格型号</span><input :value="[skuFor(line)?.model,skuFor(line)?.configuration].filter(Boolean).join(' / ')" disabled></label><label><span>单位</span><input :value="skuFor(line)?.unit??''" disabled></label><label :class="{'field-invalid':lineError(index,'quantity')}"><span>订单数量 <small v-if="lineError(index,'quantity')" class="field-error">数量须大于 0</small></span><input v-model.number="line.quantity" type="number" min="1"></label><label><span>已发货数量</span><input :value="line.shippedQuantity??0" disabled></label><label><span>剩余数量</span><input :value="line.remainingQuantity??line.quantity" disabled></label><label :class="{'field-invalid':lineError(index,'price')}"><span>含税单价 <small v-if="lineError(index,'price')" class="field-error">单价不可为负</small></span><input v-model.number="line.salePrice" type="number" min="0" step="0.01"></label><button type="button" @click="remove(index)">删除</button></div></div></div></section>
<footer><button type="button" class="secondary-action" @click="emit('close')">取消操作</button><button class="primary-action" :disabled="saving">确认保存</button></footer></form></section></div></template>
